# Appveyor: for producing Windows builds
#---------------------------------------

# Test against this version of Node.js
environment:
  nodejs_version: "8.11.1"

platform:
  - x64

# fetch repository as zip archive
shallow_clone: true

init:
  - git config --global core.autocrlf input

install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

build_script:
  - echo 'no build'

test_script:
  - npm test

